FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv pip install --system

COPY . .

EXPOSE 8000

CMD ["uv", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]